version: "3.9"
networks:
  default:
    name: tp_final_network
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: "zipkin"
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3.7.2-management
    container_name: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
  mongodb:
    image: mongo
    container_name: "mongodb"
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    ports:
      - "27017:27017"
  mysqldb:
    image: mysql
    container_name: "mysqldb"
    restart: always
    environment:
      - MYSQL_DATABASE=tp_final
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: "redis"
    ports:
      - "6379:6379"
  eureka-service:
    image: eureka-service
    container_name: "eureka-service"
    ports:
      - "8761:8761"
    restart: always
  config-service:
    image: config-service
    container_name: "config-service"
    ports:
      - "8888:8888"
    restart: always
  api-gateway:
    image: api-gateway
    container_name: "api-gateway"
    ports:
      - "8080:8080"
    restart: always
  movie-service:
    image: movie-service
    ports:
      - "8082:8082"
    restart: always
  series-service:
    image: series-service
    ports:
      - "8084:8084"
    restart: always
  catalog-service:
    image: catalog-service
    ports:
      - "8086:8086"
    restart: always
  volumes:
    data: { }